# Generated by Django 3.0 on 2020-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('B', 'Books'), ('A', 'Accessories'), ('OT', 'Other'), ('E', 'Equipment')], max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
