# Generated by Django 3.0 on 2020-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_myfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavorite',
            name='pName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
