# Generated by Django 3.0 on 2020-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20201109_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
