# Generated by Django 3.0 on 2020-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_auto_20201110_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('E', 'Engineering'), ('L', 'Law'), ('AE', 'Architecture'), ('DY', 'Dentisty'), ('LA', 'Liberal Art'), ('PS', 'Political Science'), ('M', 'Medicine')], max_length=2),
        ),
    ]
