# Generated by Django 3.0 on 2020-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_auto_20201112_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.FileField(default='dafault1.jpg', upload_to='product_pics'),
        ),
    ]
