# Generated by Django 3.0 on 2020-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_auto_20201113_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=30)),
            ],
        ),
    ]
