# Generated by Django 3.0 on 2020-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.CharField(max_length=30)),
                ('uID', models.CharField(max_length=30)),
                ('pName', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
