# Generated by Django 3.0 on 2020-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_auto_20201113_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place1',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='product',
            name='place2',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='product',
            name='place3',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
