# Generated by Django 3.0 on 2020-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_auto_20201113_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default2.png', upload_to='profile_pics'),
        ),
    ]
