# Generated by Django 3.0 on 2020-11-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_auto_20201114_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time1',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='product',
            name='time2',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='product',
            name='time3',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
