# Generated by Django 3.0 on 2020-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_auto_20201114_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='day1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='day2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='day3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='place1',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='product',
            name='place2',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='product',
            name='place3',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='product',
            name='s1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='s2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='time1',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='time2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='time3',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
