# Generated by Django 3.0 on 2020-11-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20201115_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ownerName',
            new_name='ownerID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
