# Generated by Django 3.0 on 2020-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20201114_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time3',
        ),
    ]
