# Generated by Django 3.0 on 2020-11-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_auto_20201114_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=10)),
            ],
        ),
    ]
