# Generated by Django 3.0 on 2020-11-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0016_product_ownername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ownerID',
        ),
    ]
