# Generated by Django 3.0 on 2020-11-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_remove_product_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ownerID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
