# Generated by Django 3.0 on 2020-11-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_auto_20201114_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time3',
        ),
    ]
