# Generated by Django 3.0 on 2020-11-16 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0018_product_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MyFavorite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
