# Generated by Django 3.0 on 2020-11-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_product_myfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFavorite',
        ),
    ]
