# Generated by Django 3.0 on 2020-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_auto_20201114_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='s1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='s2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='s3',
            field=models.BooleanField(default=False),
        ),
    ]
