# Generated by Django 3.0 on 2020-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0020_delete_myfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerID', models.CharField(max_length=30)),
                ('sellerID', models.CharField(max_length=30)),
                ('productID', models.CharField(max_length=30)),
            ],
        ),
    ]
