# Generated by Django 3.0 on 2020-11-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
        migrations.AddField(
            model_name='product',
            name='buyerID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
