# Generated by Django 3.0 on 2020-11-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0022_auto_20201119_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyerID',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
