# Generated by Django 3.0 on 2020-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0023_auto_20201119_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyerName',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
