# Generated by Django 3.0 on 2020-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0024_product_buyername'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='dealplace',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='product',
            name='dealtime',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
